services:
  app1:
    build:
      context:  order.service
    container_name: app1
    network_mode: host
    ports:
      - 8081:8081
    environment:
      SERVER_PORT: 8081
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  app2:
    build:
      context: order.service
    container_name: app2
    network_mode: host
    ports:
      - 8082:8082
    environment:
      SERVER_PORT: 8082
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  app3:
    build:
      context: order.service
    container_name: app3
    network_mode: host
    ports:
      - 8083:8083
    environment:
      SERVER_PORT: 8083
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  nginx: # Load Balancer
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'